SELECT COUNT(*) FROM BASES.saber_pro_2016;
/*6864*/
SELECT COUNT(*) FROM BASES.saber_pro_2017;
/*6677*/
SELECT COUNT(*) FROM BASES.saber_pro_2018;
/*9349*/
SELECT COUNT(*) FROM BASES.saber_pro_2019;
/*10647*/
SELECT COUNT(*) FROM BASES.saber_pro_2020;
/*6870*/
SELECT COUNT(*) FROM BASES.saber_pro_2020;
/*6870*/
SELECT COUNT(*) FROM BASES.pregrado;
/*42607*/
SELECT COUNT(*) FROM BASES.postgrado;
/*9928*/

/*
MAESTRIA EN ANALITICA DE DATOS
BASES DE DATOS
Claudia Palacios
Paola Velandia
Primer Taller
*/

/*Se crea la base de datos: BASE_DATOS, con el fin de cargar las tablas correspondientes 
a la información para el análisis del aporte al valor agregado de los mecanismos y apoyos 
institucionales dados a los estudiantes durante su proceso formativo, obtenido de la comparación 
de los resultados de los graduados de la Universidad Central 2017 – 2021, en las pruebas Saber 11 
y Saber PRO.

TABLAS PARA LLEVAR A CABO EL ANALISIS:

*Tablas de datos con informacion de egresados de la Universidad Central programas de Pregrado y Posgrado (2 TABLAS):
	Las bases se componene de 37 variables, las cuales dontienen informacion de cada egresado como identificacion, 
	programa estudiado, fecga de graduacion, promedio del semestre, promedioacumulado, genero, fecha de nacimiento,
	departamento de nacimmiento.

*Tablas de datos de pruebas saber PRO con una ventana de tiempo desde 2016 hasta 2020 (5 TABLAS):
	Las bases se componen de 17 variables con informacion por competencia y por estudiante indicando el puntaje 
	obtenido en cada competencia como lo son:
		COMPETENCIAS_CIUDADANAS
		COMUNICACION_ESCRITA
		INGLES
		LECTURA_CRITICA
		RAZONAMIENTO_CUANTITATIVO

*Tablas de datos de pruebas saber 11 con una ventana de tiempo desde 2009 hasta 2021 (X TABLAS):
Las bases se componen de 87 variables con informacion de entidad educativa escolar, ciudad, estrato,
fecha de presentacion del ICFES, puntajes en cada prueba y en las competencias comparables con las pruebas 
saber PRO, estado de su proceso de admision para el programa al que se postula e informacion del programa.

Para llevar a cabo el modelo relacional se crearan en las tablas la llave primaria o llave principal compuesta por 
la variable tipo de documento y número de documento:
Campos para la Llave Principal o Primaria: TIPO_DOCUMENTO + DOCUMENTO

*/

#Estructura y volumetria de las tablas insumos para tratamiento de datos de los estudiantes de pregrado y posgrado 
#de la Universidad Central 
SELECT * FROM  BASES.PREGRADO LIMIT 2;
SELECT * FROM  BASES.POSTGRADO LIMIT 2;
SELECT COUNT(*) FROM  BASES.PREGRADO;#42607
SELECT COUNT(*) FROM  BASES.POSTGRADO;#9928

SELECT PERIODO_DE_INICIO FROM  BASES.PREGRADO LIMIT 2;
SELECT * FROM  BASES.SABER_PRO_2016 LIMIT 2;					  

DESC BASES.PREGRADO;

#DIAGRAMA MODELO DE DATOS
#CREA TABLA CON LA LLAVE PRIMARIA IDENTIFICACION
DROP TABLE BASES.PREGRADO_COSOLIDA;
CREATE TABLE BASES.PREGRADO_COSOLIDA 
SELECT CONCAT(A.TIPO_DOCUMENTO,A.DOCUMENTO) AS IDENTIFICACION
,A.*
FROM BASES.PREGRADO AS A
;
SELECT * FROM BASES.PREGRADO_COSOLIDA
;
#CREA UNA TABLA CONSOLIDANDO LAS PRUEBAS SABER PRO CON LA LLAVE IDENTICACION
SELECT * FROM BASES.SABER_PRO;


DROP TABLE BASES.SABER_PRO;
CREATE TABLE BASES.SABER_PRO 
SELECT CONCAT(A.TIPO_DOCUMENTO,A.DOCUMENTO) AS IDENTIFICACION
,'PRO_2016' AS FTE
,A.*
FROM BASES.SABER_PRO_2016 AS A
;
/*
ALTER TABLE BASES.SABER_PRO MODIFY PERCENTIL_GRUPO_REFERENCIA TEXT ;
ALTER TABLE BASES.SABER_PRO MODIFY PERDENTIL_GRUPO_REFE_MODULO TEXT ;
ALTER TABLE BASES.SABER_PRO MODIFY PERCENTIL_NCNAL_MODULO TEXT ;
ALTER TABLE BASES.SABER_PRO_2018 MODIFY PERCENTIL_NCNAL_MODULO TEXT ;
ALTER TABLE BASES.SABER_PRO_2019 MODIFY PERCENTIL_GRUPO_REFERENCIA TEXT ;
ALTER TABLE BASES.SABER_PRO_2018 MODIFY TIPO_DOCUMENTO TEXT ;
*/

INSERT INTO BASES.SABER_PRO SELECT CONCAT(A.TIPO_DOCUMENTO,A.DOCUMENTO) AS IDENTIFICACION,'PRO_2017' AS FTE ,A.* FROM BASES.SABER_PRO_2017 AS A;
INSERT INTO BASES.SABER_PRO SELECT CONCAT(A.TIPO_DOCUMENTO,A.DOCUMENTO) AS IDENTIFICACION,'PRO_2018' AS FTE ,A.* FROM BASES.SABER_PRO_2018 AS A;
INSERT INTO BASES.SABER_PRO SELECT CONCAT(A.TIPO_DOCUMENTO,A.DOCUMENTO) AS IDENTIFICACION,'PRO_2019' AS FTE ,A.* FROM BASES.SABER_PRO_2019 AS A;
INSERT INTO BASES.SABER_PRO SELECT CONCAT(A.TIPO_DOCUMENTO,A.DOCUMENTO) AS IDENTIFICACION,'PRO_2020' AS FTE ,A.* FROM BASES.SABER_PRO_2020 AS A;

SELECT COUNT(*) FROM BASES.SABER_PRO_2016;#10048
SELECT COUNT(*) FROM BASES.SABER_PRO_2017;#9588
SELECT COUNT(*) FROM BASES.SABER_PRO_2018;#9577
SELECT COUNT(*) FROM BASES.SABER_PRO_2019;#10755
SELECT COUNT(*) FROM BASES.SABER_PRO_2020;#7005
#VALIDO VOLUMETRIAS CONSOLIDADAS
SELECT FTE, COUNT(*) FROM BASES.SABER_PRO GROUP BY FTE;

DESC BASES.SABER_PRO;
SELECT * FROM  BASES.SABER_PRO LIMIT 2;
SELECT * FROM  BASES.PREGRADO_COSOLIDA LIMIT 2;	

DROP TABLE BASES.PREGRADO_COSOLIDA_1;
CREATE TABLE BASES.PREGRADO_COSOLIDA_1 	
SELECT A.*
,B.FTE AS FTE_PRO
,B.TIPO_DE_EVALUADO AS TIPO_DE_EVALUADO_PRO
,B.SNIES_PROGRAMA_ACADEMICO AS SNIES_PROGRAMA_ACADEMICO_PRO
,B.PROGRAMA AS PROGRAMA_PRO
,B.CIUDAD AS CIUDAD_PRO
,B.GRUPO_DE_REFERENCIA AS GRUPO_DE_REFERENCIA_PRO
,B.PUNTAJE_GLOBAL AS PUNTAJE_GLOBAL_PRO
,B.PERCENTIL_NCNAL_GLOBAL AS PERCENTIL_NCNAL_GLOBAL_PRO
,B.PERCENTIL_GRUPO_REFERENCIA AS PERCENTIL_GRUPO_REFERENCIA_PRO
,B.MODULO AS MODULO_PRO
,B.PUNTAJE_MODULO AS PUNTAJE_MODULO_PRO
,B.NIVEL_DESEMPENO AS NIVEL_DESEMPENO_PRO
,B.PERCENTIL_NCNAL_MODULO AS PERCENTIL_NCNAL_MODULO_PRO
,B.PERCENTIL_GRUPO_REFE_MODULO AS PERDENTIL_GRUPO_REFE_MODULO_PRO
FROM BASES.PREGRADO_COSOLIDA  AS A
left join  BASES.SABER_PRO AS B
ON A.IDENTIFICACION=B.IDENTIFICACION
;

select * from  BASES.PREGRADO_COSOLIDA ;
select count(*) from  BASES.PREGRADO_COSOLIDA ;42607;
SELECT count(*) FROM BASES.PREGRADO_COSOLIDA_1 ;80392;
SELECT * FROM BASES.PREGRADO_COSOLIDA_1 ;
SELECT * FROM BASES.saber11 ;
SELECT count(*) FROM BASES.saber11 ;


select programa_academico, modulo_pro,avg(promedio_acumulado) as prom_acum,avg(puntaje_modulo_pro) as punt_mod_pro 
from  BASES.PREGRADO_COSOLIDA_1 
group by programa_academico
,modulo_pro
;

SELECT COUNT(*) FROM BASES.PREGRADO_COSOLIDA_1 ;
#80392
SELECT COUNT(DISTINCT(IDENTIFICACION)) FROM BASES.PREGRADO_COSOLIDA_1 WHERE FTE_PRO IS NULL ;
#35663
SELECT * FROM BASES.PREGRADO_COSOLIDA_1 WHERE FTE_PRO IS NULL ;
#CC80238273
#CC33365473
SELECT * FROM BASES.SABER_PRO where identificacion in ('CC80238273','CC33365473');


	
